config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/about"

  # Defines the root path route ("/")
  # old root route
  # root "home#index"
  root "friends#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path,  notice: "Not Authorized to Edit This Friend" if @friend.nil?
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end

    def about
        # this vaiable is accessible from the app/views/home/about.html.erb view
        @about_me = "My name is Louie Williford!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control", placeholder: "John" %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control", placeholder: "Doe" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control", placeholder: "john@doe.com" %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: "form-control", placeholder: "1234567890" %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, class: "form-label" %>
    <%= form.text_field :twitter, class: "form-control", placeholder: "@twitter_handle" %>
  </div>

  <!-- this field is hidden -->
  <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>

  <div class="mb-3">
    <%= form.submit 'Submit', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">

  <td>
    <%= friend.email %>
  </td>

  <td>
    <%= "#{friend.first_name} #{friend.last_name}" %>
  </td>

  <td>
    <%= friend.phone %>
  </td>

  <td>
    <%= friend.twitter %>
  </td>

  <td>
    <%= link_to "Edit Friend", edit_friend_path(friend), class: "btn btn-warning text-white" %>
  </td>

</tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
    <%= link_to "Show this Friend", @friend, class: "btn btn-secondary" %> |
    <%= link_to "Back to Friends", friends_path, class: "btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<h1>Friends</h1>

<div id="friends">
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Name</th>
        <th scope="col">Phone</th>
        <th scope="col">Twitter</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>

        <% if friend.user == current_user %>
          <%= render friend %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New Friend", new_friend_path, class: "btn btn-success" %>
<% else %>
  <h1>Sign up now!</h1>
  <p>Create an account now to start tracking your friends!</p>
<% end %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to Friends", friends_path, class: "btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
    <div class="mb-2">
        <%= link_to "Edit Friend", edit_friend_path(@friend), class: "btn btn-warning text-white" %> |
        <%= link_to "Back to Friends", friends_path, class: "btn btn-dark" %>
    </div>

    <%= button_to "Delete Friend", @friend, method: :delete, class: "btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!-- we know this view is rendered from the home controller, in the about method -->
          <!-- run `rails routes` in the console to see the prefix - append _path to that and it will give you the route -->
          <%= link_to 'About Us', home_about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <!-- notice we use button_to instead of link_to AND explicity pass the method to this link since it calls to a DELETE endpoint -->
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link custom-nav-btn" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>
<!-- this variable is defined in the corresponding controller app/controllers/home_controller.rb -->
<p><% @about_me %></p>

app/views/home/index.html.erb
<h1>HELLO WORLD!</h1>
<p>~ this is my first Ruby on Rails webpage ~</p>

app/views/layouts/_alerts.html.erb
<div class="alert a">
</div><div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- RoR meta tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Application CSS -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <title>Friends</title>
  </head>
  <body>

    <%= render "home/header" %>

    <!-- where our view contents are rendered -->
    <div class="container">
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>
        <!-- main view contents -->
        <%= yield %>
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>